### ISSUE TITLE
最新版代码，启动后选择币种时，报错

### ISSUE THREAD

**Issue by Free-freekun** [catsats/backpack_exchange#19]
选择刷量的币种，会随机刷选择的代币。
  ！确保backpack有大于5USDC数量。
  ！确保选择的币种backpack有一定余额数量，否则会报错。
  ！如果刷wen，请确保backpack有一定数量的wen，其他代币同理。
  《按键盘空格是选择，回车是确认》
     (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
( ) SOL_USDC
 ( ) BTC_USDC
 ( ) WEN_USDC
 ( ) RENDER_USDC
 ( ) WIF_USDC
 ( ) JUP_USDC
 ( ) BONK_USDC
(Use arrow keys to reveal more choices)

 (node:6128) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at isEnterKey (C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\core\dist\cjs\lib\key.js:26:33)
    at C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\checkbox\dist\cjs\index.js:65:35
    at Generator.next (<anonymous>)
    at C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\checkbox\dist\cjs\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\checkbox\dist\cjs\index.js:4:12)
    at Object.current (C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\checkbox\dist\cjs\index.js:64:38)
    at C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\core\dist\cjs\lib\use-keypress.js:12:20
    at String.wrapped (C:\Users\HP\IdeaProjects\backpack_exchange\node_modules\@inquirer\core\dist\cjs\lib\hook-engine.js:47:29)
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)

**Comment by Free-freekun** [comment]
![微信图片_20240404110636](https://github.com/catsats/backpack_exchange/assets/23478072/28aed733-86d3-4ec4-a998-5d966a
