### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by kitsonng** [catsats/backpack_exchange#5]
```javascript
/root/backpack_exchange/index.js:96
    if (orderResultAsk?.status == "Filled" && orderResultAsk?.side == "Ask") {
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
``` 

你好，想請問一下這是什麼問題？謝謝

**Comment by catsats** [comment]
你的node版本问题 node版本要大于等于18

**Comment by kitsonng** [comment]
請問一下哪個version比較推薦？update到v20.11.1遇到另一問題
```javascript
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'got'
Require stack:
- /root/backpack_exchange/backpack_client.js
- /root/backpack_exchange/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/root/backpack_exchange/backpack_client.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/backpack_exchange/backpack_client.js',
    '/root/backpack_exchange/index.js'
  ]
}
``` 
謝謝
